In [60]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder

In [61]:
columns_to_include = [
    "MS SubClass",
    "MS Zoning",
    "Lot Area",
    "Utilities",
    "Lot Config",
    "Neighborhood",
    "Condition 1",
    "Condition 2",
    "Bldg Type",
    "House Style",
    "Overall Qual",
    "Overall Cond",
    "Year Built",
    "Year Remod/Add",
    "Exterior 1st",
    "Exterior 2nd",
    "Exter Qual",
    "Exter Cond",
    "Foundation",
    "Heating",
    "Heating QC",
    "Central Air",
    "Electrical",
    "1st Flr SF",
    "2nd Flr SF",
    "Gr Liv Area",
    "Full Bath",
    "Half Bath",
    "Bedroom AbvGr",
    "Kitchen AbvGr",
    "Kitchen Qual",
    "Functional",
    "Garage Type",
    "Garage Cars",
    "Wood Deck SF",
    "Open Porch SF",
    "Pool Area",
    "Misc Val",
    "Mo Sold",
    "Yr Sold",
    "Sale Type"
]

categorical = ["MS SubClass",
               "MS Zoning",
               "Lot Config",
               "Neighborhood",
               "Condition 1",
               "Condition 2",
               "Bldg Type",
               "House Style",
               "Exterior 1st",
               "Exterior 2nd",
               "Foundation",
               "Heating",
               "Central Air",
               "Electrical",
               "Garage Type",
               "Mo Sold",
               "Yr Sold",
               "Sale Type"]
categorical_2 = []
to_convert_numbers = ["Utilities",
                      "Exter Qual",
                      "Exter Cond",
                      "Heating QC",
                      "Kitchen Qual",
                      "Functional"
]

rating_conversion = {
    "AllPub": 3,
    "NoSewr": 2,
    "NoSeWa": 1,
    "ELO": 0,
    "Ex": 4,
    "Gd": 3,
    "TA": 2,
    "Fa": 1,
    "Po": 0,
    "Typ": 7,
    "Min1": 6,
    "Min2": 5,
    "Mod": 4,
    "Maj1": 3,
    "Maj2": 2,
    "Sev": 1,
    "Sal": 0
}

In [62]:
len(categorical) + len(categorical_2)

18

In [68]:
train = pd.read_csv('datasets/train.csv')
test = pd.read_csv('datasets/test.csv')

In [53]:
len(train.columns)

82

In [54]:
len(test.columns)

81

In [82]:
filtered_train = train[columns_to_include]
filtered_test = test[columns_to_include]

In [56]:
len(filtered_train.columns)

41

In [57]:
len(filtered_test.columns)

41

In [83]:
categorical_train = filtered_train[categorical]
ohc = OneHotEncoder(handle_unknown='ignore', drop='first')
ohc.fit(categorical_train)
encoded_train = pd.DataFrame(ohc.transform(categorical_train).toarray(), columns=ohc.get_feature_names_out())

In [84]:
filtered_train.drop(columns=categorical, inplace=True)
filtered_train = pd.concat([filtered_train, encoded_train], axis=1)
filtered_train.head()

/var/folders/xc/bw1zddcx3f58lp0vxlymm23h0000gn/T/ipykernel_4856/2962744961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_train.drop(columns=categorical, inplace=True)

,Lot Area,Utilities,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Heating QC,1st Flr SF,...,Yr Sold_2009,Yr Sold_2010,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_WD
0,10667,AllPub,6,6,1971,1971,TA,TA,TA,1587,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12888,AllPub,7,8,1937,1980,TA,Gd,TA,1262,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7200,AllPub,5,8,1950,2002,TA,TA,Gd,864,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,14000,AllPub,7,5,1996,1997,Gd,TA,Ex,1306,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,11929,AllPub,8,7,1995,1995,Gd,TA,Ex,1251,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [86]:
categorical_test = filtered_test[categorical]
encoded_test = pd.DataFrame(ohc.transform(categorical_test).toarray(), columns=ohc.get_feature_names_out())
filtered_test.drop(columns=categorical, inplace=True)
filtered_test = pd.concat([filtered_test, encoded_test], axis=1)
filtered_test.head()

/Users/sangeetsatpathy/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/var/folders/xc/bw1zddcx3f58lp0vxlymm23h0000gn/T/ipykernel_4856/410143979.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_test.drop(columns=categorical, inplace=True)

,Lot Area,Utilities,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Heating QC,1st Flr SF,...,Yr Sold_2009,Yr Sold_2010,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_WD
0,10780,AllPub,5,5,1976,1976,TA,TA,Gd,954,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,14200,AllPub,7,6,1966,1966,TA,TA,Ex,1216,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,8899,AllPub,8,5,2007,2007,Ex,TA,Ex,948,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,6858,AllPub,6,4,1915,1950,TA,TA,TA,841,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,8581,AllPub,7,5,2006,2006,Gd,TA,Ex,851,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [79]:
#for col_name in categorical:
#    print(f"Now on: {col_name}")
#    data_of_col = filtered_train[col_name]
#    filtered_train.drop(columns=[col_name], inplace=True)
#    ohc = pd.get_dummies(data_of_col, drop_first=True)
#    filtered_train = pd.concat([filtered_train, ohc], axis=1)

#for col_name in categorical:
 #   print(f"Now on: {col_name}")
  #  data_of_col = filtered_test[col_name]
#    filtered_test.drop(columns=[col_name], inplace=True)
#    ohc = pd.get_dummies(data_of_col, drop_first=True)
#    filtered_test = pd.concat([filtered_test, ohc], axis=1)
#filtered_test.head()

In [98]:
print(len(filtered_train.columns))
print(len(filtered_test.columns)) # I need to stop making the test dataframe one hot encoded based on its own values; rather, I should go by the train dataframe.

170
170

In [99]:
#for col_name in categorical_2:
#    print(f"Now on: {col_name}")
#    data_of_col = filtered_train[col_name]
#    filtered_train.drop(columns=[col_name], inplace=True)
#    ohc = pd.get_dummies(data_of_col, drop_first = True)
#    filtered_train = pd.concat([filtered_train, ohc], axis = 1)

#for col_name in categorical_2:
#    print(f"Now on: {col_name}")
#    data_of_col = filtered_test[col_name]
#    filtered_test.drop(columns=[col_name], inplace=True)
#    ohc = pd.get_dummies(data_of_col, drop_first = True)
#    filtered_test = pd.concat([filtered_test, ohc], axis = 1)
#filtered_test.head()

In [100]:
#filtered_test.to_csv("datasets/filtered_houses_test.csv", index=False)

In [87]:
def numerify_ratings(x):
    return rating_conversion[x]
for c in to_convert_numbers:
    filtered_train[c] = filtered_train[c].apply(numerify_ratings)
    filtered_test[c] = filtered_test[c].apply(numerify_ratings)
filtered_train.head()

,Lot Area,Utilities,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Heating QC,1st Flr SF,...,Yr Sold_2009,Yr Sold_2010,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_WD
0,10667,3,6,6,1971,1971,2,2,2,1587,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12888,3,7,8,1937,1980,2,3,2,1262,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7200,3,5,8,1950,2002,2,2,3,864,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,14000,3,7,5,1996,1997,3,2,4,1306,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,11929,3,8,7,1995,1995,3,2,4,1251,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [88]:
filtered_train.to_csv("datasets/filtered_houses_train.csv", index=False)

In [89]:
filtered_test.to_csv("datasets/filtered_houses_test.csv", index=False)

In [118]:
filtered_test[filtered_test.isnull().any(axis=1)] # Only one column has null values, so it is fine to just ignore this entry.

,Lot Area,Utilities,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Heating QC,1st Flr SF,...,Yr Sold_2009,Yr Sold_2010,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_WD
132,9060,3,5,6,1923,1999,2,2,4,942,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [119]:
filtered_train[filtered_train.isnull().any(axis=1)]

Empty DataFrame
Columns: [Lot Area, Utilities, Overall Qual, Overall Cond, Year Built, Year Remod/Add, Exter Qual, Exter Cond, Heating QC, 1st Flr SF, 2nd Flr SF, Gr Liv Area, Full Bath, Half Bath, Bedroom AbvGr, Kitchen AbvGr, Kitchen Qual, Functional, Garage Cars, Wood Deck SF, Open Porch SF, Pool Area, Misc Val, MS SubClass_30, MS SubClass_40, MS SubClass_45, MS SubClass_50, MS SubClass_60, MS SubClass_70, MS SubClass_75, MS SubClass_80, MS SubClass_85, MS SubClass_90, MS SubClass_120, MS SubClass_150, MS SubClass_160, MS SubClass_180, MS SubClass_190, MS Zoning_C (all), MS Zoning_FV, MS Zoning_RH, MS Zoning_RL, MS Zoning_RM, Lot Config_CulDSac, Lot Config_FR2, Lot Config_FR3, Lot Config_Inside, Neighborhood_Blueste, Neighborhood_BrDale, Neighborhood_BrkSide, Neighborhood_ClearCr, Neighborhood_CollgCr, Neighborhood_Crawfor, Neighborhood_Edwards, Neighborhood_Gilbert, Neighborhood_Greens, Neighborhood_GrnHill, Neighborhood_IDOTRR, Neighborhood_Landmrk, Neighborhood_MeadowV, Neighborhood_Mitchel, Neighborhood_NAmes, Neighborhood_NPkVill, Neighborhood_NWAmes, Neighborhood_NoRidge, Neighborhood_NridgHt, Neighborhood_OldTown, Neighborhood_SWISU, Neighborhood_Sawyer, Neighborhood_SawyerW, Neighborhood_Somerst, Neighborhood_StoneBr, Neighborhood_Timber, Neighborhood_Veenker, Condition 1_Feedr, Condition 1_Norm, Condition 1_PosA, Condition 1_PosN, Condition 1_RRAe, Condition 1_RRAn, Condition 1_RRNe, Condition 1_RRNn, Condition 2_Feedr, Condition 2_Norm, Condition 2_PosA, Condition 2_PosN, Condition 2_RRAn, Condition 2_RRNn, Bldg Type_2fmCon, Bldg Type_Duplex, Bldg Type_Twnhs, Bldg Type_TwnhsE, House Style_1.5Unf, House Style_1Story, House Style_2.5Fin, House Style_2.5Unf, House Style_2Story, House Style_SFoyer, House Style_SLvl, Exterior 1st_AsphShn, ...]
Index: []

[0 rows x 170 columns]

In [90]:
X = pd.read_csv("datasets/filtered_houses_train.csv")
Y = pd.read_csv("datasets/train.csv")["SalePrice"]
X

,Lot Area,Utilities,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Heating QC,1st Flr SF,...,Yr Sold_2009,Yr Sold_2010,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_WD
0,10667,3,6,6,1971,1971,2,2,2,1587,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12888,3,7,8,1937,1980,2,3,2,1262,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7200,3,5,8,1950,2002,2,2,3,864,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,14000,3,7,5,1996,1997,3,2,4,1306,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,11929,3,8,7,1995,1995,3,2,4,1251,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,9709,3,8,5,2007,2007,4,2,4,958,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1534,9000,3,6,5,1956,1956,2,2,3,1196,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1535,10140,3,6,6,1974,1999,2,2,1,1309,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1536,1869,3,6,6,1970,1970,2,2,2,483,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1537,9100,3,7,5,2000,2000,3,2,4,1525,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [91]:
Y

0       167300
1       219000
2       129000
3       328000
4       290000
         ...
1533    319500
1534    139000
1535    181000
1536    106000
1537    235000
Name: SalePrice, Length: 1538, dtype: int64

In [92]:
lr = LinearRegression()
lr.fit(X, Y)

LinearRegression()

In [93]:
preds = lr.predict(X)

In [94]:
mean_squared_error(Y, preds)

788831355.582347

In [95]:
filtered_test_set = pd.read_csv("datasets/filtered_houses_test.csv")
filtered_test_set.columns

Index(['Lot Area', 'Utilities', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Exter Qual', 'Exter Cond', 'Heating QC',
       '1st Flr SF',
       ...
       'Yr Sold_2009', 'Yr Sold_2010', 'Sale Type_CWD', 'Sale Type_Con',
       'Sale Type_ConLD', 'Sale Type_ConLI', 'Sale Type_ConLw',
       'Sale Type_New', 'Sale Type_Oth', 'Sale Type_WD '],
      dtype='object', length=170)

In [41]:
X.columns

Index(['Lot Area', 'Utilities', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Exter Qual', 'Exter Cond', 'Heating QC',
       '1st Flr SF',
       ...
       '2009', '2010', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth',
       'WD '],
      dtype='object', length=169)

In [121]:
lr_submission = lr.predict(filtered_test_set.dropna())
lr_submission

array([134636.56527619, 225220.20928886, 318776.22197795, 120602.28450012,
       216757.60134145, 388756.58938807, 158256.80155556, 291217.69617244,
       157117.6429497 , 111209.47267641, 103153.07190999, 233854.18778263,
       196351.63361492, 118904.41986316, 122503.17234251, 104548.30145033,
        86224.72686485, 198685.97779267, 356645.20436116, 232377.27485453,
       259083.16545539, 244918.52225695, 137130.85483998, 139205.14101154,
       137890.61623699, 267908.39762635, 201892.94219258, 146725.08708901,
       292060.74356188, 110161.32772361, 340668.46498375, 108753.71233272,
       114596.79735253, 188950.14947713, 213042.02114552, 101368.36477358,
       195699.94176397, 217958.72860243, 359771.88944698, 117973.89467974,
       264480.1061341 , 209053.51918674, 321703.16306135, 173478.20387285,
        69800.84131057, 159417.41385932,  97239.16767661, 114900.06194905,
       325495.07644843, 123392.20853954, 330846.68021065,  81632.68327251,
       139892.01331856,  95394.31414872, 129489.01847723,  92349.7163755 ,
       225348.95301435, 209225.64334695, 127255.87562242, 133678.14829201,
       317205.96198305,  93759.62707062, 151187.85541146, 234315.46039018,
       190838.53365806,  48380.87905368, 268087.32893805, 254300.60235774,
       282445.46186539, 145662.11526368, 193515.52172382, 338888.6678468 ,
       312567.44461275, 204787.34859156, 118395.00792476, 211567.18723562,
       206371.66731125, 159958.31445487, 138340.83127999, 336606.58853396,
       111321.61665975,  72303.36501167, 304408.69792224, 163734.99000116,
       120489.60769251, 112742.92902991, 101118.5338622 , 221954.50027681,
        92664.50916415, 142204.42765073, 225656.71870007, 150757.56769161,
       104734.73487148, 212150.6321561 , 182170.56880559, 207932.46440748,
       151177.27389108, 138099.71888331, 191526.87923481, 153157.69530821,
       146466.92022903, 288915.30555668, 101156.48475698, 187293.60313067,
       180309.25356793, 144350.86590895, 129675.90446329, 130257.46038926,
       147784.00892905, 174050.60734925,  56714.37403941, 181643.94682372,
       129753.87841983, 333551.99179288,  88844.76243743, 228748.39243085,
       194812.58322033, 145963.8877928 , 162385.75614822, 148004.229702  ,
       207040.74969422, 118462.37999411, 248813.37787893, 125935.82567904,
       230241.35923812, 241742.08064437, 133895.20940034, 238969.32573853,
       229667.44689781, 133263.18551796, 180051.71472335, 118073.03823285,
       373870.24671529, 129941.04071219, 163731.74574553,  63124.77536187,
       146073.31438479, 164763.95568014, 210684.34828556,  78654.22103711,
        45804.54884153, 145085.26771394,  80473.55743309, 224696.17244945,
       195345.77786446, 380564.77853474, 180592.01514861, 109294.93260832,
       167472.33484927,  84886.05668926, 124220.60632977, 175583.10961684,
       225045.28568283, 126076.55394447, 176416.47552072, 251817.90315607,
       140778.44988966, 138926.44532722, 204306.40606384, 126644.01806726,
       245863.07953388, 109091.89480959, 188483.49741269, 103029.95093693,
       186752.69322048, 139369.03550125, 184888.51198191, 164780.09719536,
       282825.75330092, 239035.59696199, 142424.0681298 , 132861.1644084 ,
       198516.61705357, 109239.45663174, 152076.46943979, 289161.77623636,
       121349.1939121 , 141993.23681716, 129061.6081062 , 244319.31747253,
       159020.25350245, 174739.97932647, 166700.84894605, 125586.74518221,
       174291.36125729, 195484.42461221, 180640.86006483, 158971.97502407,
       121931.37117681, 232845.2027454 ,  92055.35271326, 145915.71300058,
        13695.89334193, 172748.03155986, 199065.97164873,  76139.61749709,
       375838.66380041, 191398.19843459, 256703.92667332, 218465.24033021,
       126089.69705732, 187997.07035053, 168225.67227798,  93835.91311124,
       113384.20927183, 137462.32007789, 128966.98243226, 127536.63041088,
       199419.32141512, 134837.94710589, 375766.32536464, 112092.36688366,
       165865.37667114, 429744.64432779, 196907.04009329, 275662.72195322,
       143585.73032332, 242659.98942467, 106390.26185898, 121255.04242393,
       179046.27603655, 165464.93497229, 178179.98324943,  98711.38682478,
       216038.45632834, 215452.70037631,  94312.94445825, 110374.95508989,
       186458.82012613, 127726.87133824, 140260.65897182, 167039.90962854,
       160728.20963441, 161997.54720441,  90458.1748504 , 217691.30386732,
       133566.38780417, 153353.75309111, 215091.78266816, 226711.0388772 ,
       154762.07028683, 115372.05059376, 160476.07743421, 131909.11530333,
       212384.66919165, 289459.45020676, 194244.69366368, 153743.4679033 ,
       221194.88071248, 248334.49116597, 327175.37847728, 277430.92798367,
       283299.10994484, 306668.04491377, 124837.49593993, 211573.03136839,
       100844.23227318, 360348.05578153, 234440.23479103, 302938.09603653,
        95960.90342835, 205052.20492098, 189779.84164351, 325912.2830208 ,
       168781.88344116, 185638.37102573, 164031.66242724, 116383.34964335,
       334956.4785039 , 124312.00265221, 143309.44578776, 104481.49079545,
       240374.71208545, 170753.66978251, 398709.42647204, 354656.96826901,
       192596.30044516, 201670.60289797, 157867.13639172,  95384.12084397,
       177732.63859511, 174753.12443161, 152879.51701402,  36028.68427666,
       239516.31276499, 109400.74449415,  79937.0587087 , 135610.6055882 ,
       216009.03946449, 215091.78266816, 176433.92253657, 121754.95159102,
       155450.88198866, 162270.66986968, 185328.19378245, 102943.87658524,
       102482.66878714, 169460.25825284, 229829.25956691, 135881.07933425,
       301390.12935841, 249502.28129941, 158738.25984615, 202490.13032195,
       231867.09100188, 154143.75968125, 199654.8148221 , 164342.81787888,
       168277.94632655,  99516.05484797,  90886.58437257, 138299.20318788,
        93155.85869527, 156968.87242924, 216573.08565025, 205505.40011874,
       111401.64836679, 221738.43059072, 194319.29257736, 226168.40702515,
       113246.12007099, 169108.06982055, 169820.80787511, 166297.06015323,
        97186.76478097, 139374.00914009, 176814.72942439, 246367.83286268,
       111869.71610388, 125123.95890679, 139669.76155816, 202734.51569382,
       330334.50282545, 146003.50534324, 100326.85459739, 387532.99170651,
       172419.56150504, 357575.74899865, 233223.0059079 , 200188.60196904,
       154114.73830213, 148870.53511414, 287804.14915361, 244612.99933624,
       140734.04264184, 116476.26667766, 280543.76548499,  32994.5355236 ,
        99761.25445411,  90898.35102585, 100572.04918258, 118826.09928656,
       320739.96696275, 330748.65769052, 158399.75611528, 301360.62625449,
       268365.72773389,  31723.0259919 , 158071.73515737, 241106.47432902,
       357117.45546476, 175632.00531584, 138217.14722064, 275262.98768693,
       215450.79047711, 238574.73966407, 215832.44409781, 261018.4545946 ,
       327946.55076133, 120198.46662884, 116507.08197295, 218167.10118251,
       185310.50417195, 142952.05488537, 317123.35670423,  99943.02290471,
       165232.55236132, 198545.92756391, 163512.55583031,  97585.41230063,
       189691.12444473, 282339.93647454, 214791.4092935 , 235796.77516499,
       117599.49510517, 140779.30800393, 215724.16773332, 133736.92015079,
       135440.04626544, 102700.50671232, 287894.10200569, 199225.24012868,
       163947.39656873, 213936.06531133, 188300.01236082, 138038.9176156 ,
       252176.97949154, 231017.74775255, 122078.9754377 , 130413.31858844,
       171525.47599885, 210785.58555118, 157225.77706299, 142348.28354123,
       210102.40777761, 218376.21867747,  73038.88626111, 330998.63763207,
       240041.37219005, 287751.07051285, 218580.21566779, 343961.09063812,
       197709.93495289, 291815.12046585, 217038.75355896, 187455.07856198,
        86295.31930694, 140727.173218  , 121599.00686258, 355120.83043208,
       230264.05344072, 135795.28875164, 220387.08454503, 105060.92953611,
       215112.55735415, 102853.58897885, 110496.40462764, 349214.81181042,
       247387.94331631, 304768.94757089, 280949.99356267,  98320.90459318,
       194566.6896715 ,  60443.89258317, 139402.67099267, 289545.99375156,
       329547.73520359, 230326.97866685, 104160.5999815 , 146689.23080037,
       124272.13632635, 139321.39538622, 136376.91203172, 256915.33721285,
       252521.53977915, 173136.89442898, 218537.04575176, 215240.84410016,
       278433.62396232, 182730.81940218, 154707.27621329, 146603.50596697,
       205525.03096773, 155087.87316686,  81327.40747693, 443185.75465093,
       288086.27753313, 317251.16386438, 241411.68683576, 213698.82563213,
       118213.52834916, 211091.43509814, 241264.45130556, 143754.69860814,
       141122.50973338,  83196.9358693 , 215558.21086972, 225191.61427414,
       163761.96039382, 238717.07447803,  96702.98511763, 341730.94389039,
       136721.58146953, 134622.07967454, 377029.67870037, 229492.2669815 ,
       108630.99392758, 124560.46137186, 214039.92270133, 116768.49426039,
       108218.1349662 , 212475.56763317, 125347.16051782, 132325.14654556,
       340141.61591798, 178436.21447587, 290521.7672653 , 182144.03823041,
       235956.94467107, 129456.65452541, 170771.05324858, 237478.57210522,
       101905.144046  , 124428.9579099 , 228494.48568253, 129062.09744106,
        82998.58649015, 204242.52882093, 173448.17531595, 121910.54611812,
       171426.79206556, 299676.50378732, 155027.95521986, 162778.26832991,
       214543.78486384, 247140.02359247, 104661.9035316 , 134938.58837003,
       105047.48205163, 113492.27602864, 130460.5231059 , 247738.80215058])