# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('../data/original_data/train.csv')
test = pd.read_csv('../data/original_data/test.csv')

In [3]:
train.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500

In [4]:
train.shape

(2051, 81)

In [5]:
test.shape

(878, 80)

In [6]:
train.describe()

,Id,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2051.000000,2.051000e+03,2051.000000,1721.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2029.000000,...,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000,2051.000000
mean,1474.033642,7.135900e+08,57.008776,69.055200,10065.208191,6.112140,5.562165,1971.708922,1984.190151,99.695909,...,93.833740,47.556802,22.571916,2.591419,16.511458,2.397855,51.574354,6.219893,2007.775719,181469.701609
std,843.980841,1.886918e+08,42.824223,23.260653,6742.488909,1.426271,1.104497,30.177889,21.036250,174.963129,...,128.549416,66.747241,59.845110,25.229615,57.374204,37.782570,573.393985,2.744736,1.312014,79258.659352
min,1.000000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,753.500000,5.284581e+08,20.000000,58.000000,7500.000000,5.000000,5.000000,1953.500000,1964.500000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129825.000000
50%,1486.000000,5.354532e+08,50.000000,68.000000,9430.000000,6.000000,5.000000,1974.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,162500.000000
75%,2198.000000,9.071801e+08,70.000000,80.000000,11513.500000,7.000000,6.000000,2001.000000,2004.000000,161.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2930.000000,9.241520e+08,190.000000,313.000000,159000.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,547.000000,432.000000,508.000000,490.000000,800.000000,17000.000000,12.000000,2010.000000,611657.000000

In [7]:
sorted_columns = sorted(train.columns)

In [8]:
column_list=[]

for col in sorted_columns:
    column_list.append((col, train[col].dtype))

column_list

[('1st Flr SF', dtype('int64')),
 ('2nd Flr SF', dtype('int64')),
 ('3Ssn Porch', dtype('int64')),
 ('Alley', dtype('O')),
 ('Bedroom AbvGr', dtype('int64')),
 ('Bldg Type', dtype('O')),
 ('Bsmt Cond', dtype('O')),
 ('Bsmt Exposure', dtype('O')),
 ('Bsmt Full Bath', dtype('float64')),
 ('Bsmt Half Bath', dtype('float64')),
 ('Bsmt Qual', dtype('O')),
 ('Bsmt Unf SF', dtype('float64')),
 ('BsmtFin SF 1', dtype('float64')),
 ('BsmtFin SF 2', dtype('float64')),
 ('BsmtFin Type 1', dtype('O')),
 ('BsmtFin Type 2', dtype('O')),
 ('Central Air', dtype('O')),
 ('Condition 1', dtype('O')),
 ('Condition 2', dtype('O')),
 ('Electrical', dtype('O')),
 ('Enclosed Porch', dtype('int64')),
 ('Exter Cond', dtype('O')),
 ('Exter Qual', dtype('O')),
 ('Exterior 1st', dtype('O')),
 ('Exterior 2nd', dtype('O')),
 ('Fence', dtype('O')),
 ('Fireplace Qu', dtype('O')),
 ('Fireplaces', dtype('int64')),
 ('Foundation', dtype('O')),
 ('Full Bath', dtype('int64')),
 ('Functional', dtype('O')),
 ('Garage Area', dtype('float64')),
 ('Garage Cars', dtype('float64')),
 ('Garage Cond', dtype('O')),
 ('Garage Finish', dtype('O')),
 ('Garage Qual', dtype('O')),
 ('Garage Type', dtype('O')),
 ('Garage Yr Blt', dtype('float64')),
 ('Gr Liv Area', dtype('int64')),
 ('Half Bath', dtype('int64')),
 ('Heating', dtype('O')),
 ('Heating QC', dtype('O')),
 ('House Style', dtype('O')),
 ('Id', dtype('int64')),
 ('Kitchen AbvGr', dtype('int64')),
 ('Kitchen Qual', dtype('O')),
 ('Land Contour', dtype('O')),
 ('Land Slope', dtype('O')),
 ('Lot Area', dtype('int64')),
 ('Lot Config', dtype('O')),
 ('Lot Frontage', dtype('float64')),
 ('Lot Shape', dtype('O')),
 ('Low Qual Fin SF', dtype('int64')),
 ('MS SubClass', dtype('int64')),
 ('MS Zoning', dtype('O')),
 ('Mas Vnr Area', dtype('float64')),
 ('Mas Vnr Type', dtype('O')),
 ('Misc Feature', dtype('O')),
 ('Misc Val', dtype('int64')),
 ('Mo Sold', dtype('int64')),
 ('Neighborhood', dtype('O')),
 ('Open Porch SF', dtype('int64')),
 ('Overall Cond', dtype('int64')),
 ('Overall Qual', dtype('int64')),
 ('PID', dtype('int64')),
 ('Paved Drive', dtype('O')),
 ('Pool Area', dtype('int64')),
 ('Pool QC', dtype('O')),
 ('Roof Matl', dtype('O')),
 ('Roof Style', dtype('O')),
 ('Sale Type', dtype('O')),
 ('SalePrice', dtype('int64')),
 ('Screen Porch', dtype('int64')),
 ('Street', dtype('O')),
 ('TotRms AbvGrd', dtype('int64')),
 ('Total Bsmt SF', dtype('float64')),
 ('Utilities', dtype('O')),
 ('Wood Deck SF', dtype('int64')),
 ('Year Built', dtype('int64')),
 ('Year Remod/Add', dtype('int64')),
 ('Yr Sold', dtype('int64'))]

In [9]:
train.isna().sum().sort_values(ascending=False).head(25)

Pool QC           2042
Misc Feature      1986
Alley             1911
Fence             1651
Mas Vnr Type      1240
Fireplace Qu      1000
Lot Frontage       330
Garage Qual        114
Garage Finish      114
Garage Yr Blt      114
Garage Cond        114
Garage Type        113
Bsmt Exposure       58
BsmtFin Type 2      56
Bsmt Cond           55
Bsmt Qual           55
BsmtFin Type 1      55
Mas Vnr Area        22
Bsmt Half Bath       2
Bsmt Full Bath       2
Garage Area          1
Total Bsmt SF        1
Bsmt Unf SF          1
BsmtFin SF 2         1
BsmtFin SF 1         1
dtype: int64

In [10]:
test.isna().sum().sort_values(ascending=False).head(25)

Pool QC           874
Misc Feature      837
Alley             820
Fence             706
Mas Vnr Type      535
Fireplace Qu      422
Lot Frontage      160
Garage Yr Blt      45
Garage Finish      45
Garage Qual        45
Garage Cond        45
Garage Type        44
BsmtFin Type 1     25
Bsmt Qual          25
Bsmt Cond          25
Bsmt Exposure      25
BsmtFin Type 2     25
Electrical          1
Mas Vnr Area        1
Kitchen AbvGr       0
TotRms AbvGrd       0
Bedroom AbvGr       0
Half Bath           0
Full Bath           0
Bsmt Half Bath      0
dtype: int64

In [11]:
#Cleaning Function
def cleaner(df):
    df['Pool QC'].fillna('no_pool', inplace = True)
    df['Misc Feature'].fillna('none', inplace = True)
    df['Alley'].fillna('no_alley_access', inplace = True)
    df['Fence'].fillna('no_fence', inplace = True)
    df['Mas Vnr Type'].fillna('none', inplace = True)
    df['Fireplace Qu'].fillna('no_fireplace', inplace = True)
    df['Garage Cond'].fillna('no_garage', inplace = True)
    df['Garage Qual'].fillna('no_garage', inplace = True)
    df['Garage Finish'].fillna('no_garage', inplace = True)
    df['Garage Yr Blt'].fillna(0, inplace = True)
    df['Lot Frontage'].fillna(0, inplace = True)
    df['Garage Type'].fillna('no_garage', inplace = True)
    df['Bsmt Exposure'].fillna('no_basement', inplace = True)
    df['BsmtFin Type 2'].fillna('no_basement', inplace = True)
    df['BsmtFin Type 1'].fillna('no_basement', inplace = True)
    df['Bsmt Cond'].fillna('no_basement', inplace = True)
    df['Bsmt Qual'].fillna('no_basement', inplace = True)
    df['Bsmt Full Bath'].fillna(0, inplace = True)
    df['Bsmt Half Bath'].fillna(0, inplace = True)
    df['Mas Vnr Area'].fillna(0, inplace = True)
    df['Electrical'].fillna('Mix', inplace = True)
    df['Garage Cars'].fillna(0, inplace = True)
    df['Total Bsmt SF'].fillna(0, inplace = True)
    df['Bsmt Unf SF'].fillna(0, inplace = True)
    df['BsmtFin SF 2'].fillna(0, inplace = True)
    df['BsmtFin SF 1'].fillna(0, inplace = True)
    df['Garage Area'].fillna(0, inplace = True)
    
    return df

In [12]:
train_clean = cleaner(train)

In [13]:
test_clean = cleaner(test)

In [14]:
train_clean.shape

(2051, 81)

In [15]:
test_clean.shape

(878, 80)

In [16]:
train_clean.to_csv('../data/cleaned_data/train_clean.csv', index=False)

In [17]:
test_clean.to_csv('../data/cleaned_data/test_clean.csv', index=False)